name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'

jobs:
  # Quick validation for PRs
  pr-checks:
    runs-on: ubuntu-latest
    name: PR Quality Checks
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd client && npm ci
          cd ../server && npm ci
      
      - name: Lint check
        run: |
          cd client && npm run lint
      
      - name: Type check
        run: |
          cd client && npm run build
          cd ../server && npm run build
      
      - name: Unit tests
        run: |
          cd server && npm test
          cd ../client && npm test -- --run
        env:
          DATABASE_URL: "file:./test.db"
      
      - name: PR Summary
        run: |
          echo "✅ All PR checks passed!"
          echo "- Code quality: ✅"
          echo "- Type safety: ✅" 
          echo "- Unit tests: ✅"
          echo "Ready for review! 🚀"